name: woocommerce_flutter_api
description: Woocommerce flutter api integration with external plugin created by loaidev64@gmail.com and published by amjadqasem07@gmail.com.
version: 1.0.1
repository: https://github.com/loaidev64/woocommerce_flutter_api.git
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=1.17.0"

# Add regular dependencies here.
dependencies:
  dio: ^5.4.1
  faker: ^2.1.0
  flutter_secure_storage: ^9.0.0
  pretty_dio_logger: ^1.3.1
  json_reader:
    git:
      url: git@github.com:denizz311/json_reader.git
      ref: main
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
